<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ajegu\BinanceSdk\Endpoint;

use Ajegu\BinanceSdk\Exception\UnexpectedStatusCodeException;
use Ajegu\BinanceSdk\Model\BookTickerResponse;
use Ajegu\BinanceSdk\Runtime\Client\BaseEndpoint;
use Ajegu\BinanceSdk\Runtime\Client\Endpoint;
use Ajegu\BinanceSdk\Runtime\Client\EndpointTrait;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Serializer\SerializerInterface;

class GetBookTicker extends BaseEndpoint implements Endpoint
{
    use EndpointTrait;

    /**
     * @param array $queryParameters {
     *
     *     @var string $symbol
     * }
     */
    public function __construct(array $queryParameters = [])
    {
        $this->queryParameters = $queryParameters;
    }

    public function getMethod(): string
    {
        return 'GET';
    }

    public function getUri(): string
    {
        return '/ticker/bookTicker';
    }

    public function getBody(SerializerInterface $serializer, $streamFactory = null): array
    {
        return [[], null];
    }

    public function getExtraHeaders(): array
    {
        return ['Accept' => ['application/json']];
    }

    protected function getQueryOptionsResolver(): OptionsResolver
    {
        $optionsResolver = parent::getQueryOptionsResolver();
        $optionsResolver->setDefined(['symbol']);
        $optionsResolver->setRequired(['symbol']);
        $optionsResolver->setDefaults([]);
        $optionsResolver->setAllowedTypes('symbol', ['string']);

        return $optionsResolver;
    }

    /**
     * {@inheritdoc}
     *
     * @throws UnexpectedStatusCodeException
     *
     * @return BookTickerResponse|null
     */
    protected function transformResponseBody(string $body, int $status, SerializerInterface $serializer, ?string $contentType = null)
    {
        if (is_null($contentType) === false && (200 === $status && mb_strpos($contentType, 'application/json') !== false)) {
            return $serializer->deserialize($body, 'Ajegu\\BinanceSdk\\Model\\BookTickerResponse', 'json');
        }
        throw new UnexpectedStatusCodeException($status);
    }

    public function getAuthenticationScopes(): array
    {
        return [];
    }
}
