<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ajegu\BinanceSdk\Normalizer;

use Ajegu\BinanceSdk\Model\BookTickerResponse;
use Ajegu\BinanceSdk\Runtime\Normalizer\CheckArray;
use Jane\JsonSchemaRuntime\Reference;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use function array_key_exists;
use function is_array;

class BookTickerResponseNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;

    public function supportsDenormalization($data, $type, $format = null)
    {
        return $type === 'Ajegu\\BinanceSdk\\Model\\BookTickerResponse';
    }

    public function supportsNormalization($data, $format = null)
    {
        return is_object($data) && get_class($data) === 'Ajegu\\BinanceSdk\\Model\\BookTickerResponse';
    }

    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (isset($data['$ref'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        $object = new BookTickerResponse();
        if (null === $data || false === is_array($data)) {
            return $object;
        }
        if (array_key_exists('symbol', $data)) {
            $object->setSymbol($data['symbol']);
        }
        if (array_key_exists('bidPrice', $data)) {
            $object->setBidPrice($data['bidPrice']);
        }
        if (array_key_exists('askPrice', $data)) {
            $object->setAskPrice($data['askPrice']);
        }

        return $object;
    }

    public function normalize($object, $format = null, array $context = [])
    {
        $data = [];
        if (null !== $object->getSymbol()) {
            $data['symbol'] = $object->getSymbol();
        }
        if (null !== $object->getBidPrice()) {
            $data['bidPrice'] = $object->getBidPrice();
        }
        if (null !== $object->getAskPrice()) {
            $data['askPrice'] = $object->getAskPrice();
        }

        return $data;
    }
}
