<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ajegu\BinanceSdk\Model;

class BookTickerResponse
{
    /**
     * @var string
     */
    protected $symbol;
    /**
     * @var string
     */
    protected $bidPrice;
    /**
     * @var string
     */
    protected $askPrice;

    public function getSymbol(): string
    {
        return $this->symbol;
    }

    public function setSymbol(string $symbol): self
    {
        $this->symbol = $symbol;

        return $this;
    }

    public function getBidPrice(): string
    {
        return $this->bidPrice;
    }

    public function setBidPrice(string $bidPrice): self
    {
        $this->bidPrice = $bidPrice;

        return $this;
    }

    public function getAskPrice(): string
    {
        return $this->askPrice;
    }

    public function setAskPrice(string $askPrice): self
    {
        $this->askPrice = $askPrice;

        return $this;
    }
}
