<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ajegu\BinanceSdk\Exception;

use Throwable;

interface ApiException extends Throwable
{
}
